# Original podman image.
# =====================================================
FROM quay.io/podman/stable as original
COPY ./Containerfile ./run.sh /home/podman/
RUN chmod +x /home/podman/*.sh

RUN date | md5sum | cut -d ' ' -f 1 > /image.version
WORKDIR /home/podman

# Alpine podman image.
# =====================================================
FROM alpine:latest as custom
RUN apk update && apk add git
RUN apk add bash jq curl findutils

RUN apk add crun shadow openrc fuse-overlayfs shadow slirp4netns

RUN rc-service cgroups start || true
RUN rc-update add cgroups
RUN apk add podman

RUN temp=$(mktemp) && \
    sed -E 's/rc_cgroup_mode=.*/rc_cgroup_mode="unified"/g' /etc/rc.conf >"\$temp" && \
    mv "\$temp" /etc/rc.conf

RUN adduser "podman" \
    -D \
    -u "1000" -g "1000" \
    -h "/home/podman" && \
    echo -e "podman:1:999\npodman:1001:64535" > /etc/subuid && \
    echo -e "podman:1:999\npodman:1001:64535" > /etc/subgid

ARG _REPO_URL="https://raw.githubusercontent.com/containers/image_build/main/podman"
ADD $_REPO_URL/containers.conf /etc/containers/containers.conf
ADD $_REPO_URL/podman-containers.conf /home/podman/.config/containers/containers.conf

RUN mkdir -p /home/podman/.local/share/containers && \
    chown podman:podman -R /home/podman && \
    chmod 644 /etc/containers/containers.conf

# Copy & modify the defaults to provide reference if runtime changes needed.
# Changes here are required for running with fuse-overlay storage inside container.
RUN sed -e 's|^#mount_program|mount_program|g' \
           -e '/additionalimage.*/a "/var/lib/shared",' \
           -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
           /usr/share/containers/storage.conf \
           > /etc/containers/storage.conf

# Setup internal Podman to pass subscriptions down from host to internal container
RUN printf '/run/secrets/etc-pki-entitlement:/run/secrets/etc-pki-entitlement\n/run/secrets/rhsm:/run/secrets/rhsm\n' > /etc/containers/mounts.conf

# Note VOLUME options must always happen after the chown call above
# RUN commands can not modify existing volumes
VOLUME /var/lib/containers
VOLUME /home/podman/.local/share/containers

RUN mkdir -p /var/lib/shared/overlay-images \
             /var/lib/shared/overlay-layers \
             /var/lib/shared/vfs-images \
             /var/lib/shared/vfs-layers \
             /run/secrets/etc-pki-entitlement \
             /run/secrets/rhsm && \
    touch /var/lib/shared/overlay-images/images.lock && \
    touch /var/lib/shared/overlay-layers/layers.lock && \
    touch /var/lib/shared/vfs-images/images.lock && \
    touch /var/lib/shared/vfs-layers/layers.lock

COPY ./Containerfile ./run.sh /home/podman/
RUN chmod +x /home/podman/*.sh

RUN date | md5sum | cut -d ' ' -f 1 > /image.version
WORKDIR /home/podman
